//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Olimp2019.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class OlimpResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OlimpResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Olimp2019.Web.Resources.OlimpResource", typeof(OlimpResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Бали.
        /// </summary>
        public static string GamePage_Score_Label {
            get {
                return ResourceManager.GetString("GamePage_Score_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вихід.
        /// </summary>
        public static string Global_Exit {
            get {
                return ResourceManager.GetString("Global_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дії.
        /// </summary>
        public static string Reports_Action {
            get {
                return ResourceManager.GetString("Reports_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поштова адреса.
        /// </summary>
        public static string Reports_Email {
            get {
                return ResourceManager.GetString("Reports_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Повне ім&apos;я.
        /// </summary>
        public static string Reports_FullName {
            get {
                return ResourceManager.GetString("Reports_FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Логін.
        /// </summary>
        public static string Reports_Login {
            get {
                return ResourceManager.GetString("Reports_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Звіт.
        /// </summary>
        public static string Reports_Report {
            get {
                return ResourceManager.GetString("Reports_Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назва звіту.
        /// </summary>
        public static string Reports_ReportName {
            get {
                return ResourceManager.GetString("Reports_ReportName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Звіт по користувачам.
        /// </summary>
        public static string Reports_ReportUser {
            get {
                return ResourceManager.GetString("Reports_ReportUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Передивитись.
        /// </summary>
        public static string Reports_View {
            get {
                return ResourceManager.GetString("Reports_View", resourceCulture);
            }
        }
    }
}
